name: Default
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20.x'
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: pip install git+https://github.com/aws/aws-cli.git@2.16.2
