name: Default
on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20.x'
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.11'
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm test
      - name: Setup SSH config
        run: |
          mkdir -p ~/.ssh; echo -e 'Host colo-contabo-1.gslin.com\n    IdentityFile ~/.ssh/deploy.pem\n    Port 222\n    StrictHostKeyChecking accept-new\n' > ~/.ssh/config
      - name: Setup SSH private key
        env:
          DEPLOY_SSH_PRIVATE_KEY_BASE64: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p ~/.ssh; echo -n "$DEPLOY_SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/deploy.pem; chmod 600 ~/.ssh/deploy.pem
      - name: Deploy to server
        run: |
          rsync -Favz --delete-after ./ service-test@colo-contabo-1.gslin.com:test-githubactions/
      - name: Install fnm
        run: |
          ssh service-test@colo-contabo-1.gslin.com 'command -v fnm || ( cd /tmp; wget https://github.com/Schniz/fnm/releases/download/v1.37.0/fnm-linux.zip; mkdir ~/.fnm; unzip fnm-linux.zip -d ~/.fnm/; chmod 755 ~/.fnm/fnm )'
      - name: Restart services
        # Use workaround to load fnm.
        run: |
          ssh service-test@colo-contabo-1.gslin.com 'eval "$(${HOME}/.fnm/fnm env --use-on-cd)" && export PATH="${HOME}/.fnm:${PATH}"; cd test-githubactions; npx pm2 restart ecosystem.config.js'
