name: Default
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --no-audit
      - run: npm test
