name: Default
on:
  push:
    branches:
      - main
env:
  DEPLOY_HOSTNAME_MAIN: colo-contabo-1.gslin.com
  PROJECT_NAME: ${{ github.event.repository.name }}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20.x'
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.11'

      - name: Setup environment variables based on branches
        run: |
          echo "DEPLOY_HOSTNAME=${DEPLOY_HOSTNAME_$(echo ${GITHUB_REF_NAME} | tr a-z A-Z)}" >> "${GITHUB_ENV}"

      - run: npm install --no-audit
      - run: npm run lint
      - run: npm test

      - name: Setup SSH config
        run: |
          mkdir -p ~/.ssh; echo -e "Host ${DEPLOY_HOSTNAME}\n    IdentityFile ~/.ssh/deploy.pem\n    Port 222\n    StrictHostKeyChecking accept-new\n    User service-${PROJECT_NAME}" > ~/.ssh/config
      - name: Setup SSH private key
        env:
          DEPLOY_SSH_PRIVATE_KEY_BASE64: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY_BASE64 }}
        run: |
          mkdir -p ~/.ssh; echo -n "${DEPLOY_SSH_PRIVATE_KEY_BASE64}" | base64 -d > ~/.ssh/deploy.pem; chmod 600 ~/.ssh/deploy.pem
      - name: Deploy to server
        run: |
          rsync -Favz --delete-after ./ "${DEPLOY_HOSTNAME}:${PROJECT_NAME}/"

      - name: Run setup.sh remotely
        run: |
          ssh "${DEPLOY_HOSTNAME}" "cd ~/${PROJECT_NAME}; scripts/setup.sh"
